export type DesignCategory =
  | "wedding"
  | "engagement"
  | "circumcision"
  | "birthday"
  | "business";

export const CATEGORIES: { key: DesignCategory | "all"; label: string }[] = [
  { key: "wedding", label: "Düğün" },
  { key: "engagement", label: "Nikah" },
  { key: "circumcision", label: "Sünnet Düğünü" },
  { key: "birthday", label: "Çocuk Doğum Günü" },
  { key: "business", label: "İşyeri Açılışı" },
  { key: "all", label: "Tüm Kategoriler" },
];

export type DesignTheme =
  | "ivory-daisy"
  | "blush-rose"
  | "noir-gold"
  | "sage-botanical"
  | "terracotta"
  | "midnight-gold"
  | "pastel-mint"
  | "blush-gold"
  | "cobalt-classic"
  | "sand-minimal"
  | "forest-deep"
  | "lavender-soft"
  | "bronze-boho"
  | "ocean-modern"
  | "cream-elegance"
  | "rose-gold-luxe";

/**
 * Distinct top-of-card layout variants. Each sample references one of these
 * so the preview + real card renderer can draw a visibly different frame
 * without every design needing a custom component.
 *
 *  - classic:         simple frame, text centered, decorative strokes
 *  - arch:            tall arched (cathedral) frame behind the names
 *  - photo-top:       hero photograph occupies top half, text sits below
 *  - photo-full:      photo fills the whole card with soft dark overlay
 *  - floral-crown:    arc of florals across the top
 *  - monogram-circle: circular monogram badge + names orbiting it
 *  - bold-type:       oversized display names, minimal ornament
 *  - botanical-frame: leaves growing along the vertical edges
 */
export type DesignLayout =
  | "classic"
  | "arch"
  | "photo-top"
  | "photo-full"
  | "floral-crown"
  | "monogram-circle"
  | "bold-type"
  | "botanical-frame";

/** Outer-card top silhouette options the gallery and editor share.
 *  Mirrors `CardShape` in @davety/schema but kept duplicated here so the
 *  gallery files don't need to import the schema package. */
export type DesignCardShape =
  | "flat"
  | "arch"
  | "tall-arch"
  | "rounded"
  | "peaked"
  | "chevron"
  | "tag";

export interface DesignSample {
  id: string;
  code: string; // e.g. "GPCU"
  name: string; // style name (Türkçe)
  category: DesignCategory;
  theme: DesignTheme;
  layout: DesignLayout;
  /** Outer card silhouette. Decoupled from `layout` so a sample can use
   *  e.g. classic typography but still get a peaked/tag/arch outer shape. */
  cardShape?: DesignCardShape;
  bg: string;
  accent: string;
  textColor: string;
  decorative: "daisy" | "rose" | "gold" | "none";
  envelopeColor: string;
  liningBg: string;
  liningPattern: "daisy" | "rose" | "gold" | "none" | "chevron";
  flapColor?: string;
  /** Optional hero image used by photo-top / photo-full layouts. */
  photoUrl?: string;
  sampleBride: string;
  sampleGroom: string;
  subtitle: string;
  /** Asset key inside `/public/assets/templates/` — e.g.
   *  `"wedding-essentials/wedding-essentials-01"`. Galeri kartı bu SVG'yi
   *  CSS `mask-image` ile tema vurgu rengine boyayarak isimlerin üstüne
   *  süsleme olarak yerleştirir. `buildDesignDoc` aynı dosyayı disk'ten
   *  okuyup hero'nun altına bir `decoration` block'u olarak ekler — yani
   *  galeri ile editör aynı süsü gösterir. */
  decorationTemplate?: string;
}

/** Build a full stock URL for a known Unsplash photo id. */
function photo(id: string): string {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;
}

/** Resolve the card silhouette for a sample. Samples that don't pin a
 *  `cardShape` fall back to a sensible default per layout — arch layouts
 *  get an arched silhouette, monogram circles get rounded corners, photo
 *  layouts stay flat so the photo isn't clipped, etc. */
export function shapeFor(sample: DesignSample): DesignCardShape {
  if (sample.cardShape) return sample.cardShape;
  switch (sample.layout) {
    case "arch":
      return "arch";
    case "monogram-circle":
      return "rounded";
    case "floral-crown":
      return "tall-arch";
    case "botanical-frame":
      return "arch";
    default:
      return "flat";
  }
}

/** Friendly Turkish labels for the card-shape selector in the editor. */
export const CARD_SHAPE_LABELS: Record<DesignCardShape, string> = {
  flat: "Düz",
  arch: "Klasik Kemer",
  "tall-arch": "Yüksek Kemer",
  rounded: "Yuvarlak Köşe",
  peaked: "Üçgen Tepe",
  chevron: "V Kesim",
  tag: "Etiket",
};

/** Eski tasarım koleksiyonu — yeni V2 setine geçilmeden önceki kayıtlar.
 *  Hâlâ doc'unda eski bir id taşıyan kullanıcılar için lookup fallback'i
 *  olarak duruyor (`/api/design/invitations` route'u önce yeni listeye,
 *  bulamazsa buraya bakar). UI'a artık servis edilmiyor. */
export const LEGACY_DESIGN_SAMPLES: DesignSample[] = [
  {
    id: "d-1",
    code: "GPCU",
    name: "Papatya Esintisi",
    category: "wedding",
    theme: "ivory-daisy",
    layout: "floral-crown",
    bg: "#fbf7ee",
    accent: "#c9a35a",
    textColor: "#4a3f2e",
    decorative: "daisy",
    envelopeColor: "#f5f1e8",
    liningBg: "#1f1c17",
    liningPattern: "daisy",
    sampleBride: "Havva",
    sampleGroom: "İbrahim",
    subtitle: "Aşkın Başladığı Gün",
  },
  {
    id: "d-2",
    code: "KPTZ",
    name: "Monogram Arch",
    category: "wedding",
    theme: "sand-minimal",
    layout: "arch",
    bg: "#f3efe6",
    accent: "#7d6b4f",
    textColor: "#3c3528",
    decorative: "gold",
    envelopeColor: "#efe9dc",
    liningBg: "#2a241b",
    liningPattern: "gold",
    sampleBride: "Fadime",
    sampleGroom: "Osman",
    subtitle: "Aşkın Ritmi",
  },
  {
    id: "d-3",
    code: "PBMH",
    name: "Botanik Sade",
    category: "engagement",
    theme: "sage-botanical",
    layout: "botanical-frame",
    bg: "#eef1ea",
    accent: "#5a6b4d",
    textColor: "#32392d",
    decorative: "rose",
    envelopeColor: "#eaede3",
    liningBg: "#2d3628",
    liningPattern: "rose",
    sampleBride: "Yağmur",
    sampleGroom: "Ahmet",
    subtitle: "Birlikte Daha Güçlü",
  },
  {
    id: "d-4",
    code: "PNBU",
    name: "Altın Buket",
    category: "wedding",
    theme: "blush-gold",
    layout: "floral-crown",
    bg: "#faf3ea",
    accent: "#b38a4a",
    textColor: "#4a3822",
    decorative: "gold",
    envelopeColor: "#f5eddd",
    liningBg: "#1b160e",
    liningPattern: "gold",
    sampleBride: "Ela",
    sampleGroom: "İbrahim",
    subtitle: "Birlikte Daha Güçlü",
  },
  {
    id: "d-5",
    code: "VIED",
    name: "Arch Klasik",
    category: "wedding",
    theme: "cream-elegance",
    layout: "arch",
    bg: "#faf5e8",
    accent: "#a78a3e",
    textColor: "#3e3723",
    decorative: "gold",
    envelopeColor: "#f6eed9",
    liningBg: "#1f1a0e",
    liningPattern: "gold",
    sampleBride: "Sultan",
    sampleGroom: "Yusuf",
    subtitle: "Sonsuza Kadar Evet",
  },
  {
    id: "d-6",
    code: "PZVM",
    name: "Boho Hatıra",
    category: "engagement",
    theme: "bronze-boho",
    layout: "photo-top",
    cardShape: "rounded",
    bg: "#efe4d2",
    accent: "#8a5a2b",
    textColor: "#3d2a15",
    decorative: "rose",
    envelopeColor: "#ecdcc2",
    liningBg: "#3a2414",
    liningPattern: "rose",
    photoUrl: photo("photo-1525772764200-be829a350797"),
    sampleBride: "Deniz",
    sampleGroom: "Kaan",
    subtitle: "Birlikte Yürüyoruz",
  },
  {
    id: "d-7",
    code: "LBTR",
    name: "İnce Çember",
    category: "engagement",
    theme: "pastel-mint",
    layout: "monogram-circle",
    bg: "#eef4ee",
    accent: "#4c7a66",
    textColor: "#2a3a32",
    decorative: "none",
    envelopeColor: "#e7efe7",
    liningBg: "#24352d",
    liningPattern: "chevron",
    sampleBride: "Ayşe",
    sampleGroom: "Rıza",
    subtitle: "İki Kalp Bir Yürek",
  },
  {
    id: "d-8",
    code: "JTSY",
    name: "Işıltı",
    category: "wedding",
    theme: "rose-gold-luxe",
    layout: "photo-full",
    cardShape: "tag",
    bg: "#f7eee4",
    accent: "#b87a56",
    textColor: "#4a2f20",
    decorative: "gold",
    envelopeColor: "#f2e6d4",
    liningBg: "#2a1a10",
    liningPattern: "gold",
    photoUrl: photo("photo-1519741497674-611481863552"),
    sampleBride: "Belinay",
    sampleGroom: "Salih",
    subtitle: "Birlikte Daha Güçlü",
  },
  {
    id: "d-9",
    code: "PJNT",
    name: "Gece Altını",
    category: "wedding",
    theme: "midnight-gold",
    layout: "bold-type",
    cardShape: "chevron",
    bg: "#141210",
    accent: "#d4a94a",
    textColor: "#f0e4c2",
    decorative: "gold",
    envelopeColor: "#1a1713",
    liningBg: "#f0e4c2",
    liningPattern: "gold",
    flapColor: "#1a1713",
    sampleBride: "Şerife",
    sampleGroom: "Berat",
    subtitle: "Aşkın Ritmi",
  },
  {
    id: "d-10",
    code: "DNRP",
    name: "Masal",
    category: "wedding",
    theme: "cream-elegance",
    layout: "arch",
    bg: "#fbf5ea",
    accent: "#a88442",
    textColor: "#3f3120",
    decorative: "gold",
    envelopeColor: "#f6ecd6",
    liningBg: "#211a0f",
    liningPattern: "gold",
    sampleBride: "Masalımız",
    sampleGroom: "Başlıyor",
    subtitle: "Hayalimizdeki Gün",
  },
  {
    id: "d-11",
    code: "CKMR",
    name: "Küçük Sultan",
    category: "circumcision",
    theme: "cobalt-classic",
    layout: "classic",
    bg: "#e9edf5",
    accent: "#2e4a8a",
    textColor: "#16213f",
    decorative: "gold",
    envelopeColor: "#dde3ef",
    liningBg: "#0f1a36",
    liningPattern: "gold",
    sampleBride: "Ömer",
    sampleGroom: "Sünnet",
    subtitle: "Mutlu Günümüze Buyurun",
  },
  {
    id: "d-12",
    code: "ASLN",
    name: "Aslan Yürekli",
    category: "circumcision",
    theme: "noir-gold",
    layout: "bold-type",
    bg: "#15130f",
    accent: "#e0b85a",
    textColor: "#f3e4b8",
    decorative: "gold",
    envelopeColor: "#1a1713",
    liningBg: "#e0b85a",
    liningPattern: "gold",
    flapColor: "#1a1713",
    sampleBride: "Ali",
    sampleGroom: "Prensi",
    subtitle: "Şimdi Koca Adam",
  },
  {
    id: "d-13",
    code: "MINI",
    name: "Pamuk Şeker",
    category: "birthday",
    theme: "lavender-soft",
    layout: "floral-crown",
    bg: "#f4eaf4",
    accent: "#a56bb5",
    textColor: "#4a2e50",
    decorative: "rose",
    envelopeColor: "#efdfef",
    liningBg: "#4a2e50",
    liningPattern: "rose",
    sampleBride: "Zeynep",
    sampleGroom: "5 Yaş",
    subtitle: "Neşe Dolu Bir Gün",
  },
  {
    id: "d-14",
    code: "CIRC",
    name: "Sirk Zamanı",
    category: "birthday",
    theme: "terracotta",
    layout: "photo-top",
    bg: "#f5ded0",
    accent: "#c45a3e",
    textColor: "#4a2218",
    decorative: "none",
    envelopeColor: "#f0d2bf",
    liningBg: "#4a2218",
    liningPattern: "chevron",
    photoUrl: photo("photo-1527529482837-4698179dc6ce"),
    sampleBride: "Emir",
    sampleGroom: "Doğum Günü",
    subtitle: "Eğlence Başlasın",
  },
  {
    id: "d-15",
    code: "LINK",
    name: "Modern Açılış",
    category: "business",
    theme: "ocean-modern",
    layout: "bold-type",
    cardShape: "peaked",
    bg: "#e7eff3",
    accent: "#1f5a7a",
    textColor: "#0f2a3a",
    decorative: "none",
    envelopeColor: "#dbe6ed",
    liningBg: "#0f2a3a",
    liningPattern: "chevron",
    sampleBride: "Atölye",
    sampleGroom: "İstanbul",
    subtitle: "Açılışa Davetlisiniz",
  },
  {
    id: "d-16",
    code: "PROA",
    name: "Prestij",
    category: "business",
    theme: "forest-deep",
    layout: "classic",
    bg: "#e4ece5",
    accent: "#214735",
    textColor: "#14291e",
    decorative: "gold",
    envelopeColor: "#d9e4db",
    liningBg: "#14291e",
    liningPattern: "gold",
    sampleBride: "Brand&Co",
    sampleGroom: "Lansman",
    subtitle: "Yeni Bir Başlangıç",
  },

  /* ── New layout-driven variants ───────────────────────────────── */
  {
    id: "d-17",
    code: "ARCH",
    name: "Katedral Arch",
    category: "wedding",
    theme: "cream-elegance",
    layout: "arch",
    bg: "#f4ebd8",
    accent: "#8c6f3a",
    textColor: "#3a2e18",
    decorative: "gold",
    envelopeColor: "#efe4c9",
    liningBg: "#1b140b",
    liningPattern: "gold",
    sampleBride: "Nisa",
    sampleGroom: "Mert",
    subtitle: "Yolumuz Bir Oldu",
  },
  {
    id: "d-18",
    code: "PHFR",
    name: "Fotoğraf Çerçevesi",
    category: "wedding",
    theme: "blush-rose",
    layout: "photo-top",
    bg: "#fbeae2",
    accent: "#b85a6b",
    textColor: "#4a2026",
    decorative: "rose",
    envelopeColor: "#f5ddd4",
    liningBg: "#3a1620",
    liningPattern: "rose",
    photoUrl: photo("photo-1523348837708-15d4a09cfac2"),
    sampleBride: "Elif",
    sampleGroom: "Emre",
    subtitle: "Bugün Başlıyoruz",
  },
  {
    id: "d-19",
    code: "FULL",
    name: "Tam Portre",
    category: "wedding",
    theme: "bronze-boho",
    layout: "photo-full",
    bg: "#2b1e12",
    accent: "#e0bd87",
    textColor: "#f5e8cf",
    decorative: "gold",
    envelopeColor: "#ecdcc2",
    liningBg: "#e0bd87",
    liningPattern: "gold",
    flapColor: "#ecdcc2",
    photoUrl: photo("photo-1549417229-7686ac5595fd"),
    sampleBride: "Ceren",
    sampleGroom: "Barış",
    subtitle: "Bir Macera",
  },
  {
    id: "d-20",
    code: "MONO",
    name: "Dairesel Monogram",
    category: "wedding",
    theme: "sand-minimal",
    layout: "monogram-circle",
    bg: "#f0eadd",
    accent: "#6f5a33",
    textColor: "#2b2415",
    decorative: "gold",
    envelopeColor: "#eadfc5",
    liningBg: "#1d1709",
    liningPattern: "gold",
    sampleBride: "Aylin",
    sampleGroom: "Kerem",
    subtitle: "İki Yolda Bir Son",
  },
  {
    id: "d-21",
    code: "BOTF",
    name: "Botanik Kenar",
    category: "engagement",
    theme: "sage-botanical",
    layout: "botanical-frame",
    bg: "#e9efe1",
    accent: "#465c3a",
    textColor: "#1f2b18",
    decorative: "rose",
    envelopeColor: "#dfe7d4",
    liningBg: "#1a2213",
    liningPattern: "rose",
    sampleBride: "Zehra",
    sampleGroom: "Cem",
    subtitle: "Yaşamımız Çiçeklensin",
  },
  {
    id: "d-22",
    code: "BOLD",
    name: "Büyük Tipografi",
    category: "business",
    theme: "ocean-modern",
    layout: "bold-type",
    bg: "#f4f4f4",
    accent: "#101820",
    textColor: "#101820",
    decorative: "none",
    envelopeColor: "#e8e8e8",
    liningBg: "#101820",
    liningPattern: "chevron",
    sampleBride: "Studio",
    sampleGroom: "No.42",
    subtitle: "Grand Opening",
  },
  {
    id: "d-23",
    code: "CRWN",
    name: "Çiçekli Taç",
    category: "birthday",
    theme: "blush-rose",
    layout: "floral-crown",
    bg: "#fdeeeb",
    accent: "#c27a6d",
    textColor: "#4a1f18",
    decorative: "rose",
    envelopeColor: "#f8dfd9",
    liningBg: "#4a1f18",
    liningPattern: "rose",
    sampleBride: "Mira",
    sampleGroom: "3 Yaş",
    subtitle: "Minik Bir Kutlama",
  },
  {
    id: "d-24",
    code: "ARPH",
    name: "Arch + Fotoğraf",
    category: "wedding",
    theme: "blush-gold",
    layout: "photo-top",
    bg: "#fbf1e5",
    accent: "#a77a3e",
    textColor: "#3d2a14",
    decorative: "gold",
    envelopeColor: "#f4e6cd",
    liningBg: "#2a1c0c",
    liningPattern: "gold",
    photoUrl: photo("photo-1519741347686-c1e0aadf4611"),
    sampleBride: "İrem",
    sampleGroom: "Doruk",
    subtitle: "Birlikte Daha Güçlü",
  },
  {
    id: "d-25",
    code: "BHRZ",
    name: "Bohem Hazan",
    category: "wedding",
    theme: "terracotta",
    layout: "botanical-frame",
    bg: "#fbf2e8",
    accent: "#a35a35",
    textColor: "#3a1f12",
    decorative: "rose",
    envelopeColor: "#f0d9c2",
    liningBg: "#3a1f12",
    liningPattern: "rose",
    sampleBride: "Defne",
    sampleGroom: "Berk",
    subtitle: "Yapraklar Düşerken",
  },
  {
    id: "d-26",
    code: "MNGM",
    name: "Monogram Lüks",
    category: "wedding",
    theme: "noir-gold",
    layout: "monogram-circle",
    bg: "#1a1714",
    accent: "#d4b886",
    textColor: "#f5ecd9",
    decorative: "gold",
    envelopeColor: "#231e1a",
    liningBg: "#0d0b09",
    liningPattern: "gold",
    sampleBride: "Selin",
    sampleGroom: "Mehmet",
    subtitle: "Sonsuza Dek",
  },
  {
    id: "d-27",
    code: "DLAV",
    name: "Lavanta Esintisi",
    category: "wedding",
    theme: "lavender-soft",
    layout: "floral-crown",
    bg: "#f5f2fb",
    accent: "#5b4b8a",
    textColor: "#2e2447",
    decorative: "rose",
    envelopeColor: "#e4ddf2",
    liningBg: "#2e2447",
    liningPattern: "rose",
    sampleBride: "Elif",
    sampleGroom: "Kerem",
    subtitle: "Bir Mucize Gibi",
  },
  {
    id: "d-28",
    code: "OKYS",
    name: "Okyanus Sade",
    category: "wedding",
    theme: "ocean-modern",
    layout: "bold-type",
    bg: "#eef4f8",
    accent: "#1e4866",
    textColor: "#0e2a3d",
    decorative: "none",
    envelopeColor: "#d9e8f2",
    liningBg: "#0e2a3d",
    liningPattern: "chevron",
    sampleBride: "Mira",
    sampleGroom: "Eren",
    subtitle: "Dalgalar Birleşince",
  },
  {
    id: "d-29",
    code: "GLBH",
    name: "Gül Bahçesi",
    category: "wedding",
    theme: "blush-rose",
    layout: "arch",
    bg: "#fdf2f4",
    accent: "#8b3a4b",
    textColor: "#4d1a26",
    decorative: "rose",
    envelopeColor: "#f5d5d9",
    liningBg: "#4d1a26",
    liningPattern: "rose",
    sampleBride: "Zeynep",
    sampleGroom: "Hasan",
    subtitle: "Aşkın Bahçesi",
  },
  {
    id: "d-30",
    code: "NSNL",
    name: "Nişan Lüksü",
    category: "engagement",
    theme: "rose-gold-luxe",
    layout: "monogram-circle",
    bg: "#fbecdd",
    accent: "#a35a3b",
    textColor: "#4a2918",
    decorative: "gold",
    envelopeColor: "#f4dec6",
    liningBg: "#4a2918",
    liningPattern: "gold",
    sampleBride: "Ada",
    sampleGroom: "Tolga",
    subtitle: "Söz Verdik",
  },
  {
    id: "d-31",
    code: "SNTR",
    name: "Sünnet Töreni",
    category: "circumcision",
    theme: "midnight-gold",
    layout: "classic",
    bg: "#1a2238",
    accent: "#d4b886",
    textColor: "#f5ecd9",
    decorative: "gold",
    envelopeColor: "#243250",
    liningBg: "#0a1124",
    liningPattern: "gold",
    sampleBride: "—",
    sampleGroom: "Yusuf",
    subtitle: "Maşallah Bu Güne",
  },
  {
    id: "d-32",
    code: "BBAY",
    name: "Bebek Bulutu",
    category: "birthday",
    theme: "pastel-mint",
    layout: "floral-crown",
    bg: "#eaf6f2",
    accent: "#3e8a78",
    textColor: "#1d4a3f",
    decorative: "daisy",
    envelopeColor: "#d3ebe2",
    liningBg: "#1d4a3f",
    liningPattern: "daisy",
    sampleBride: "—",
    sampleGroom: "Mira",
    subtitle: "Mevlüde Davetlisin",
  },
];

/**
 * Yeni V2 tasarım koleksiyonu — ana sayfada gösterilen aktif liste.
 *
 *  Her tasarım beş şeyin tutarlı olmasına dikkat eder:
 *   - `category` ↔ `sampleBride/sampleGroom` (tek-aday kategorilerde
 *     `sampleGroom: ""`, böylece galeri ve editör "&" çizmez).
 *   - `decorative` ↔ `liningPattern` (zarf astarı kart süslemesiyle
 *     aynı flavor'dan gelir).
 *   - `bg` / `accent` / `textColor` üçlüsü okunabilir kontrast verir.
 *   - `photoUrl` yalnızca `photo-top` veya `photo-full` layout'larında.
 *   - `cardShape` her kategoride 7 değerin tamamından örnek içerir
 *     (flat, arch, tall-arch, rounded, peaked, chevron, tag) ki tepe
 *     yapısı farkları galeride yan yana görülsün.
 *
 *  Kategori başına 8 örnek = toplam 40. Her tasarım
 *  `decorationTemplate` ile `/public/assets/templates/...` altındaki
 *  bir SVG'yi referanslar; galeri kart önizlemesi onu CSS mask ile,
 *  editör de aynı SVG'yi `decoration` block'unun `svgRaw`'ı olarak
 *  kullanır.
 *
 *  Eski sürüm `LEGACY_DESIGN_SAMPLES` adıyla duruyor; geri dönüş
 *  istenirse import noktasını değiştirmek yeterli.
 */
export const DESIGN_SAMPLES: DesignSample[] = [
  // ─── Düğün (8) ──────────────────────────────────────────────────
  {
    id: "v2-w-1",
    code: "WCLA",
    name: "Klasik Tören",
    category: "wedding",
    theme: "ivory-daisy",
    layout: "classic",
    cardShape: "flat",
    bg: "#faf5e9",
    accent: "#8a6f3f",
    textColor: "#3f3320",
    decorative: "daisy",
    envelopeColor: "#f1ead7",
    liningBg: "#3f3320",
    liningPattern: "daisy",
    sampleBride: "Elif",
    sampleGroom: "Yusuf",
    subtitle: "Bir Ömür Birlikte",
    decorationTemplate: "wedding-essentials/wedding-essentials-01",
  },
  {
    id: "v2-w-2",
    code: "WARC",
    name: "Altın Kemer",
    category: "wedding",
    theme: "sand-minimal",
    layout: "arch",
    cardShape: "arch",
    bg: "#f4ede0",
    accent: "#a8804a",
    textColor: "#3a2e1e",
    decorative: "gold",
    envelopeColor: "#ece3d2",
    liningBg: "#2c2418",
    liningPattern: "gold",
    sampleBride: "Defne",
    sampleGroom: "Mert",
    subtitle: "Aşkın İmzası",
    decorationTemplate: "floral-corners/floral-corners-01",
  },
  {
    id: "v2-w-3",
    code: "WCRO",
    name: "Çiçek Tacı",
    category: "wedding",
    theme: "blush-rose",
    layout: "floral-crown",
    cardShape: "tall-arch",
    bg: "#fdf2f1",
    accent: "#b86a7e",
    textColor: "#5a2c3a",
    decorative: "rose",
    envelopeColor: "#f5dadf",
    liningBg: "#5a2c3a",
    liningPattern: "rose",
    sampleBride: "Naz",
    sampleGroom: "Berk",
    subtitle: "Sözümüzü Veriyoruz",
    decorationTemplate: "wedding-essentials/wedding-essentials-05",
  },
  {
    id: "v2-w-4",
    code: "WROM",
    name: "Romantik Foto",
    category: "wedding",
    theme: "rose-gold-luxe",
    layout: "photo-top",
    cardShape: "rounded",
    bg: "#fbf0ee",
    accent: "#a85567",
    textColor: "#5a2733",
    decorative: "rose",
    envelopeColor: "#f4dad6",
    liningBg: "#5a2733",
    liningPattern: "rose",
    photoUrl: photo("photo-1519741497674-611481863552"),
    sampleBride: "Aslı",
    sampleGroom: "Kaan",
    subtitle: "Aşkın Başladığı Gün",
    decorationTemplate: "floral-corners/floral-corners-04",
  },
  {
    id: "v2-w-5",
    code: "WPEK",
    name: "Üçgen Tepe Sade",
    category: "wedding",
    theme: "sage-botanical",
    layout: "classic",
    cardShape: "peaked",
    bg: "#eef2ea",
    accent: "#5e7456",
    textColor: "#2d3a28",
    decorative: "gold",
    envelopeColor: "#e3eadd",
    liningBg: "#2d3a28",
    liningPattern: "gold",
    sampleBride: "Selin",
    sampleGroom: "Cem",
    subtitle: "İki Yürek Bir Yol",
    decorationTemplate: "wedding-essentials/wedding-essentials-08",
  },
  {
    id: "v2-w-6",
    code: "WCHV",
    name: "V Kesim Lüks",
    category: "wedding",
    theme: "midnight-gold",
    layout: "classic",
    cardShape: "chevron",
    bg: "#11132a",
    accent: "#d4b886",
    textColor: "#f3e7cd",
    decorative: "gold",
    envelopeColor: "#1a1d3a",
    liningBg: "#d4b886",
    liningPattern: "gold",
    flapColor: "#0a0c20",
    sampleBride: "Lara",
    sampleGroom: "Tuna",
    subtitle: "Yıldızlı Bir Gece",
    decorationTemplate: "gold-ornaments/gold-ornaments-04",
  },
  {
    id: "v2-w-7",
    code: "WTAG",
    name: "Etiket Modern",
    category: "wedding",
    theme: "cream-elegance",
    layout: "bold-type",
    cardShape: "tag",
    bg: "#f7f4ee",
    accent: "#1f1d1a",
    textColor: "#1f1d1a",
    decorative: "none",
    envelopeColor: "#ece7dd",
    liningBg: "#1f1d1a",
    liningPattern: "none",
    sampleBride: "Ece",
    sampleGroom: "Burak",
    subtitle: "Birlikte Yazıyoruz",
    decorationTemplate: "gold-ornaments/gold-ornaments-10",
  },
  {
    id: "v2-w-8",
    code: "WBOT",
    name: "Botanik Kemer",
    category: "wedding",
    theme: "forest-deep",
    layout: "botanical-frame",
    cardShape: "arch",
    bg: "#edf2ea",
    accent: "#2f5d3c",
    textColor: "#142b1a",
    decorative: "rose",
    envelopeColor: "#d9e4d3",
    liningBg: "#142b1a",
    liningPattern: "rose",
    sampleBride: "Yağmur",
    sampleGroom: "Ahmet",
    subtitle: "Doğanın Şahidi",
    decorationTemplate: "botanical-frames/botanical-frames-02",
  },

  // ─── Nikah (8) ─────────────────────────────────────────────────
  {
    id: "v2-e-1",
    code: "ECLA",
    name: "Lavanta Klasik",
    category: "engagement",
    theme: "lavender-soft",
    layout: "classic",
    cardShape: "flat",
    bg: "#f3effa",
    accent: "#6b5b94",
    textColor: "#2e2746",
    decorative: "gold",
    envelopeColor: "#e3dcf1",
    liningBg: "#2e2746",
    liningPattern: "gold",
    sampleBride: "Zeynep",
    sampleGroom: "Ali",
    subtitle: "Yeni Bir Sayfa",
    decorationTemplate: "engagement/engagement-01",
  },
  {
    id: "v2-e-2",
    code: "EARC",
    name: "Pudra Kemer",
    category: "engagement",
    theme: "blush-gold",
    layout: "arch",
    cardShape: "arch",
    bg: "#fbf2ec",
    accent: "#b48362",
    textColor: "#5a3a25",
    decorative: "gold",
    envelopeColor: "#f3e1d0",
    liningBg: "#5a3a25",
    liningPattern: "gold",
    sampleBride: "İrem",
    sampleGroom: "Eren",
    subtitle: "Sözümüz Bir",
    decorationTemplate: "engagement/engagement-04",
  },
  {
    id: "v2-e-3",
    code: "ECRO",
    name: "Pastel Çiçek Tacı",
    category: "engagement",
    theme: "blush-rose",
    layout: "floral-crown",
    cardShape: "tall-arch",
    bg: "#fbe9ef",
    accent: "#a3475e",
    textColor: "#5a1f31",
    decorative: "rose",
    envelopeColor: "#f4cdd6",
    liningBg: "#5a1f31",
    liningPattern: "rose",
    sampleBride: "Beren",
    sampleGroom: "Ozan",
    subtitle: "Aile Olmaya Bir Adım",
    decorationTemplate: "engagement/engagement-06",
  },
  {
    id: "v2-e-4",
    code: "EFOT",
    name: "Sıcak Foto",
    category: "engagement",
    theme: "terracotta",
    layout: "photo-top",
    cardShape: "rounded",
    bg: "#fbeee2",
    accent: "#a45a36",
    textColor: "#5a2912",
    decorative: "rose",
    envelopeColor: "#f4d8bf",
    liningBg: "#5a2912",
    liningPattern: "rose",
    photoUrl: photo("photo-1525772764200-be829a350797"),
    sampleBride: "Su",
    sampleGroom: "Deniz",
    subtitle: "Bizden Haber Var",
    decorationTemplate: "engagement/engagement-08",
  },
  {
    id: "v2-e-5",
    code: "EPEK",
    name: "Papatya Tepe",
    category: "engagement",
    theme: "ivory-daisy",
    layout: "classic",
    cardShape: "peaked",
    bg: "#fbf6e9",
    accent: "#a48438",
    textColor: "#48381c",
    decorative: "daisy",
    envelopeColor: "#f0e5c1",
    liningBg: "#48381c",
    liningPattern: "daisy",
    sampleBride: "Ada",
    sampleGroom: "Can",
    subtitle: "Sade Bir Tören",
    decorationTemplate: "engagement/engagement-09",
  },
  {
    id: "v2-e-6",
    code: "ECHV",
    name: "Modern V Kesim",
    category: "engagement",
    theme: "sand-minimal",
    layout: "bold-type",
    cardShape: "chevron",
    bg: "#f1ece1",
    accent: "#3c3225",
    textColor: "#1f1a10",
    decorative: "gold",
    envelopeColor: "#e8e0cc",
    liningBg: "#1f1a10",
    liningPattern: "gold",
    sampleBride: "Mira",
    sampleGroom: "Onat",
    subtitle: "Az Söz Çok Anlam",
    decorationTemplate: "dividers/dividers-03",
  },
  {
    id: "v2-e-7",
    code: "ETAG",
    name: "Etiket Krem",
    category: "engagement",
    theme: "cream-elegance",
    layout: "classic",
    cardShape: "tag",
    bg: "#f8f4eb",
    accent: "#7d623c",
    textColor: "#3c2d18",
    decorative: "daisy",
    envelopeColor: "#ede4cd",
    liningBg: "#3c2d18",
    liningPattern: "daisy",
    sampleBride: "Lal",
    sampleGroom: "Arda",
    subtitle: "Davetimiz Sizedir",
    decorationTemplate: "engagement/engagement-11",
  },
  {
    id: "v2-e-8",
    code: "EMON",
    name: "Lavanta Monogram",
    category: "engagement",
    theme: "lavender-soft",
    layout: "monogram-circle",
    cardShape: "rounded",
    bg: "#efeaf7",
    accent: "#5a4a85",
    textColor: "#231b40",
    decorative: "gold",
    envelopeColor: "#ddd1ee",
    liningBg: "#231b40",
    liningPattern: "gold",
    sampleBride: "Hira",
    sampleGroom: "Kuzey",
    subtitle: "Bir İmza Bir Söz",
    decorationTemplate: "floral-corners/floral-corners-07",
  },

  // ─── Sünnet Düğünü (8) — sampleGroom: "" ───────────────────────
  {
    id: "v2-c-1",
    code: "CCLA",
    name: "Mavi Klasik",
    category: "circumcision",
    theme: "cobalt-classic",
    layout: "classic",
    cardShape: "flat",
    bg: "#eef3fb",
    accent: "#234c91",
    textColor: "#162a55",
    decorative: "gold",
    envelopeColor: "#dbe4f4",
    liningBg: "#162a55",
    liningPattern: "gold",
    sampleBride: "Emir",
    sampleGroom: "",
    subtitle: "Maşallah Bu Güne",
    decorationTemplate: "circumcision-classic/circumcision-classic-01",
  },
  {
    id: "v2-c-2",
    code: "CARC",
    name: "Lacivert Altın Kemer",
    category: "circumcision",
    theme: "midnight-gold",
    layout: "arch",
    cardShape: "arch",
    bg: "#e7ecf8",
    accent: "#1f2e58",
    textColor: "#0e1532",
    decorative: "gold",
    envelopeColor: "#1f2e58",
    liningBg: "#d4b886",
    liningPattern: "gold",
    flapColor: "#0e1532",
    sampleBride: "Yiğit",
    sampleGroom: "",
    subtitle: "Sünnet Cemiyetimize Davetlisiniz",
    decorationTemplate: "circumcision-classic/circumcision-classic-03",
  },
  {
    id: "v2-c-3",
    code: "CCRO",
    name: "Mint Tacı",
    category: "circumcision",
    theme: "pastel-mint",
    layout: "floral-crown",
    cardShape: "tall-arch",
    bg: "#e8f4ee",
    accent: "#3f7a5e",
    textColor: "#1f3a2c",
    decorative: "none",
    envelopeColor: "#d6ebde",
    liningBg: "#1f3a2c",
    liningPattern: "none",
    sampleBride: "Mehmet",
    sampleGroom: "",
    subtitle: "Birlikte Kutlayalım",
    decorationTemplate: "circumcision-classic/circumcision-classic-05",
  },
  {
    id: "v2-c-4",
    code: "CRND",
    name: "Yumuşak Yuvarlak",
    category: "circumcision",
    theme: "ocean-modern",
    layout: "classic",
    cardShape: "rounded",
    bg: "#eaf2f8",
    accent: "#2a5d83",
    textColor: "#163349",
    decorative: "none",
    envelopeColor: "#d3e2ee",
    liningBg: "#163349",
    liningPattern: "chevron",
    sampleBride: "Kuzey",
    sampleGroom: "",
    subtitle: "Mutlu Günümüze Buyurun",
    decorationTemplate: "circumcision-classic/circumcision-classic-07",
  },
  {
    id: "v2-c-5",
    code: "CPEK",
    name: "Sünnet Tepe",
    category: "circumcision",
    theme: "noir-gold",
    layout: "classic",
    cardShape: "peaked",
    bg: "#1c1a16",
    accent: "#d4b886",
    textColor: "#f4ebd5",
    decorative: "gold",
    envelopeColor: "#26221c",
    liningBg: "#d4b886",
    liningPattern: "gold",
    flapColor: "#100e0a",
    sampleBride: "Mert",
    sampleGroom: "",
    subtitle: "Geleneğin İzinden",
    decorationTemplate: "gold-ornaments/gold-ornaments-06",
  },
  {
    id: "v2-c-6",
    code: "CCHV",
    name: "Şenlikli V Kesim",
    category: "circumcision",
    theme: "rose-gold-luxe",
    layout: "bold-type",
    cardShape: "chevron",
    bg: "#fdeae0",
    accent: "#b35c3a",
    textColor: "#5a2310",
    decorative: "gold",
    envelopeColor: "#f5d6c0",
    liningBg: "#5a2310",
    liningPattern: "gold",
    sampleBride: "Selim",
    sampleGroom: "",
    subtitle: "Şenliğimize Buyurun",
    decorationTemplate: "circumcision-classic/circumcision-classic-09",
  },
  {
    id: "v2-c-7",
    code: "CTAG",
    name: "Etiket Sünnet",
    category: "circumcision",
    theme: "blush-gold",
    layout: "classic",
    cardShape: "tag",
    bg: "#fbf3eb",
    accent: "#a8754a",
    textColor: "#4d2912",
    decorative: "gold",
    envelopeColor: "#f3decb",
    liningBg: "#4d2912",
    liningPattern: "gold",
    sampleBride: "Kerem",
    sampleGroom: "",
    subtitle: "Önemli Günümüzde Yanımızda Olun",
    decorationTemplate: "circumcision-classic/circumcision-classic-11",
  },
  {
    id: "v2-c-8",
    code: "CFOT",
    name: "Fotoğraflı Çocuk",
    category: "circumcision",
    theme: "cobalt-classic",
    layout: "photo-top",
    cardShape: "rounded",
    bg: "#eaf2fa",
    accent: "#1f4a85",
    textColor: "#0c2148",
    decorative: "none",
    envelopeColor: "#d2e0f0",
    liningBg: "#0c2148",
    liningPattern: "chevron",
    photoUrl: photo("photo-1527529482837-4698179dc6ce"),
    sampleBride: "Ömer",
    sampleGroom: "",
    subtitle: "Bizimle Kutlayın",
    decorationTemplate: "circumcision-classic/circumcision-classic-12",
  },

  // ─── Çocuk Doğum Günü (8) — sampleGroom: "" ────────────────────
  {
    id: "v2-b-1",
    code: "BCLA",
    name: "Pembe Klasik",
    category: "birthday",
    theme: "blush-rose",
    layout: "classic",
    cardShape: "flat",
    bg: "#fdeaef",
    accent: "#c0376a",
    textColor: "#5a1a32",
    decorative: "rose",
    envelopeColor: "#f8d3df",
    liningBg: "#5a1a32",
    liningPattern: "rose",
    sampleBride: "Mira",
    sampleGroom: "",
    subtitle: "Minik Bir Kutlama",
    decorationTemplate: "kids-party/kids-party-01",
  },
  {
    id: "v2-b-2",
    code: "BARC",
    name: "Şenlikli Kemer",
    category: "birthday",
    theme: "ocean-modern",
    layout: "arch",
    cardShape: "arch",
    bg: "#e6f2fb",
    accent: "#2f74b8",
    textColor: "#143150",
    decorative: "gold",
    envelopeColor: "#cee4f5",
    liningBg: "#143150",
    liningPattern: "chevron",
    sampleBride: "Arda",
    sampleGroom: "",
    subtitle: "5. Yaşımı Kutluyorum",
    decorationTemplate: "kids-party/kids-party-03",
  },
  {
    id: "v2-b-3",
    code: "BCRO",
    name: "Balon Tacı",
    category: "birthday",
    theme: "rose-gold-luxe",
    layout: "floral-crown",
    cardShape: "tall-arch",
    bg: "#fdf0e8",
    accent: "#d96b3a",
    textColor: "#5a2a14",
    decorative: "rose",
    envelopeColor: "#f7d8c4",
    liningBg: "#5a2a14",
    liningPattern: "rose",
    sampleBride: "Defne",
    sampleGroom: "",
    subtitle: "Eğlence Başlasın",
    decorationTemplate: "kids-party/kids-party-05",
  },
  {
    id: "v2-b-4",
    code: "BMON",
    name: "Yuvarlak Monogram",
    category: "birthday",
    theme: "pastel-mint",
    layout: "monogram-circle",
    cardShape: "rounded",
    bg: "#e8f4ee",
    accent: "#3f7a5e",
    textColor: "#1f3a2c",
    decorative: "daisy",
    envelopeColor: "#d6ebde",
    liningBg: "#1f3a2c",
    liningPattern: "daisy",
    sampleBride: "Lina",
    sampleGroom: "",
    subtitle: "Doğum Günüm Var",
    decorationTemplate: "baby-shower/baby-shower-04",
  },
  {
    id: "v2-b-5",
    code: "BPEK",
    name: "Tepe Pasta",
    category: "birthday",
    theme: "ivory-daisy",
    layout: "classic",
    cardShape: "peaked",
    bg: "#fcf4d8",
    accent: "#c08a1a",
    textColor: "#5a3e0a",
    decorative: "daisy",
    envelopeColor: "#f5e7b0",
    liningBg: "#5a3e0a",
    liningPattern: "daisy",
    sampleBride: "Berk",
    sampleGroom: "",
    subtitle: "Mum Söndürmeye Davetlisin",
    decorationTemplate: "kids-party/kids-party-07",
  },
  {
    id: "v2-b-6",
    code: "BCHV",
    name: "Mavi V Kesim",
    category: "birthday",
    theme: "ocean-modern",
    layout: "classic",
    cardShape: "chevron",
    bg: "#e6f0fa",
    accent: "#1f5a91",
    textColor: "#0a2745",
    decorative: "gold",
    envelopeColor: "#cfdfee",
    liningBg: "#0a2745",
    liningPattern: "chevron",
    sampleBride: "Tan",
    sampleGroom: "",
    subtitle: "Şenliğime Davetlisin",
    decorationTemplate: "baby-shower/baby-shower-06",
  },
  {
    id: "v2-b-7",
    code: "BTAG",
    name: "Etiket Bonbon",
    category: "birthday",
    theme: "blush-gold",
    layout: "classic",
    cardShape: "tag",
    bg: "#fbede2",
    accent: "#b86638",
    textColor: "#4d1f10",
    decorative: "gold",
    envelopeColor: "#f3d5bd",
    liningBg: "#4d1f10",
    liningPattern: "gold",
    sampleBride: "Ela",
    sampleGroom: "",
    subtitle: "3 Yaşıma Geliyorum",
    decorationTemplate: "kids-party/kids-party-10",
  },
  {
    id: "v2-b-8",
    code: "BFOT",
    name: "Renkli Foto",
    category: "birthday",
    theme: "rose-gold-luxe",
    layout: "photo-top",
    cardShape: "rounded",
    bg: "#fbeae0",
    accent: "#c25530",
    textColor: "#5a200c",
    decorative: "none",
    envelopeColor: "#f4d2bf",
    liningBg: "#5a200c",
    liningPattern: "none",
    photoUrl: photo("photo-1530103862676-de8c9debad1d"),
    sampleBride: "Doruk",
    sampleGroom: "",
    subtitle: "Birlikte Kutlayalım",
    decorationTemplate: "kids-party/kids-party-11",
  },

  // ─── İşyeri Açılışı (8) — sampleGroom: "" ──────────────────────
  {
    id: "v2-x-1",
    code: "XBLD",
    name: "Bold Açılış",
    category: "business",
    theme: "noir-gold",
    layout: "bold-type",
    cardShape: "flat",
    bg: "#f4f3f1",
    accent: "#111111",
    textColor: "#111111",
    decorative: "none",
    envelopeColor: "#1a1a1a",
    liningBg: "#d4b886",
    liningPattern: "gold",
    flapColor: "#111111",
    sampleBride: "Atölye 7",
    sampleGroom: "",
    subtitle: "Açılışımıza Davetlisiniz",
    decorationTemplate: "business-luxe/business-luxe-01",
  },
  {
    id: "v2-x-2",
    code: "XARC",
    name: "Krem Bronz Kemer",
    category: "business",
    theme: "bronze-boho",
    layout: "arch",
    cardShape: "arch",
    bg: "#f5ede0",
    accent: "#8a5a2a",
    textColor: "#3c2410",
    decorative: "gold",
    envelopeColor: "#ecdfca",
    liningBg: "#3c2410",
    liningPattern: "gold",
    sampleBride: "Atelier Café",
    sampleGroom: "",
    subtitle: "Kapımız Açılıyor",
    decorationTemplate: "gold-ornaments/gold-ornaments-02",
  },
  {
    id: "v2-x-3",
    code: "XCRO",
    name: "Lansman Tacı",
    category: "business",
    theme: "midnight-gold",
    layout: "floral-crown",
    cardShape: "tall-arch",
    bg: "#eef1f8",
    accent: "#1c2a52",
    textColor: "#0a1124",
    decorative: "gold",
    envelopeColor: "#dee3f0",
    liningBg: "#0a1124",
    liningPattern: "gold",
    sampleBride: "Mavi Ofis",
    sampleGroom: "",
    subtitle: "Yeni Mekânımızı Tanıtıyoruz",
    decorationTemplate: "business-luxe/business-luxe-03",
  },
  {
    id: "v2-x-4",
    code: "XRND",
    name: "Yuvarlak Lüks",
    category: "business",
    theme: "noir-gold",
    layout: "classic",
    cardShape: "rounded",
    bg: "#1d1c1a",
    accent: "#d4b886",
    textColor: "#f3e7cd",
    decorative: "gold",
    envelopeColor: "#272622",
    liningBg: "#d4b886",
    liningPattern: "gold",
    flapColor: "#100f0d",
    sampleBride: "Black Studio",
    sampleGroom: "",
    subtitle: "Davetimiz Sizinle",
    decorationTemplate: "gold-ornaments/gold-ornaments-08",
  },
  {
    id: "v2-x-5",
    code: "XPEK",
    name: "Tepe Profesyonel",
    category: "business",
    theme: "cobalt-classic",
    layout: "classic",
    cardShape: "peaked",
    bg: "#eaf0f8",
    accent: "#1f3d72",
    textColor: "#0d1c3a",
    decorative: "none",
    envelopeColor: "#d6e1f0",
    liningBg: "#0d1c3a",
    liningPattern: "chevron",
    sampleBride: "Polaris Co.",
    sampleGroom: "",
    subtitle: "Yeni Bir Sayfa Açıyoruz",
    decorationTemplate: "business-luxe/business-luxe-05",
  },
  {
    id: "v2-x-6",
    code: "XCHV",
    name: "V Kesim Modern",
    category: "business",
    theme: "sand-minimal",
    layout: "bold-type",
    cardShape: "chevron",
    bg: "#f1ece1",
    accent: "#3c3225",
    textColor: "#1f1a10",
    decorative: "none",
    envelopeColor: "#e8e0cc",
    liningBg: "#1f1a10",
    liningPattern: "none",
    sampleBride: "Studio Nort",
    sampleGroom: "",
    subtitle: "Tasarımla Tanışın",
    decorationTemplate: "dividers/dividers-05",
  },
  {
    id: "v2-x-7",
    code: "XTAG",
    name: "Etiket Lansman",
    category: "business",
    theme: "blush-gold",
    layout: "bold-type",
    cardShape: "tag",
    bg: "#fbf3eb",
    accent: "#8a5a2c",
    textColor: "#3c2110",
    decorative: "gold",
    envelopeColor: "#f0dec3",
    liningBg: "#3c2110",
    liningPattern: "gold",
    sampleBride: "Lumen Gallery",
    sampleGroom: "",
    subtitle: "Galerimizin Açılışı",
    decorationTemplate: "badges/badges-12",
  },
  {
    id: "v2-x-8",
    code: "XBOT",
    name: "Yeşil Doğa",
    category: "business",
    theme: "forest-deep",
    layout: "botanical-frame",
    cardShape: "flat",
    bg: "#edf1ea",
    accent: "#2f5d3c",
    textColor: "#142b1a",
    decorative: "none",
    envelopeColor: "#d9e4d3",
    liningBg: "#142b1a",
    liningPattern: "none",
    sampleBride: "Yeşil Bahçe",
    sampleGroom: "",
    subtitle: "Doğanın Kapısını Açıyoruz",
    decorationTemplate: "botanical-frames/botanical-frames-04",
  },
];
