// AUTO-GENERATED by scripts/generate-decoration-templates.mjs — do not edit by hand.
export interface DecorationTemplate {
  id: string;
  url: string;
}

export interface DecorationTemplateCategory {
  key: string;
  label: string;
  items: DecorationTemplate[];
}

export const DECORATION_TEMPLATE_CATEGORIES: DecorationTemplateCategory[] =
  [
  {
    "key": "wedding-essentials",
    "label": "Düğün Süslemeleri",
    "items": [
      {
        "id": "wedding-essentials-01",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-01.svg"
      },
      {
        "id": "wedding-essentials-02",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-02.svg"
      },
      {
        "id": "wedding-essentials-03",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-03.svg"
      },
      {
        "id": "wedding-essentials-04",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-04.svg"
      },
      {
        "id": "wedding-essentials-05",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-05.svg"
      },
      {
        "id": "wedding-essentials-06",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-06.svg"
      },
      {
        "id": "wedding-essentials-07",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-07.svg"
      },
      {
        "id": "wedding-essentials-08",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-08.svg"
      },
      {
        "id": "wedding-essentials-09",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-09.svg"
      },
      {
        "id": "wedding-essentials-10",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-10.svg"
      },
      {
        "id": "wedding-essentials-11",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-11.svg"
      },
      {
        "id": "wedding-essentials-12",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-12.svg"
      },
      {
        "id": "wedding-essentials-13",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-13.svg"
      },
      {
        "id": "wedding-essentials-14",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-14.svg"
      },
      {
        "id": "wedding-essentials-15",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-15.svg"
      },
      {
        "id": "wedding-essentials-16",
        "url": "/assets/templates/wedding-essentials/wedding-essentials-16.svg"
      }
    ]
  },
  {
    "key": "monograms",
    "label": "Monogram",
    "items": [
      {
        "id": "monograms-01",
        "url": "/assets/templates/monograms/monograms-01.svg"
      },
      {
        "id": "monograms-02",
        "url": "/assets/templates/monograms/monograms-02.svg"
      },
      {
        "id": "monograms-03",
        "url": "/assets/templates/monograms/monograms-03.svg"
      },
      {
        "id": "monograms-04",
        "url": "/assets/templates/monograms/monograms-04.svg"
      },
      {
        "id": "monograms-05",
        "url": "/assets/templates/monograms/monograms-05.svg"
      },
      {
        "id": "monograms-06",
        "url": "/assets/templates/monograms/monograms-06.svg"
      },
      {
        "id": "monograms-07",
        "url": "/assets/templates/monograms/monograms-07.svg"
      },
      {
        "id": "monograms-08",
        "url": "/assets/templates/monograms/monograms-08.svg"
      },
      {
        "id": "monograms-09",
        "url": "/assets/templates/monograms/monograms-09.svg"
      },
      {
        "id": "monograms-10",
        "url": "/assets/templates/monograms/monograms-10.svg"
      },
      {
        "id": "monograms-11",
        "url": "/assets/templates/monograms/monograms-11.svg"
      },
      {
        "id": "monograms-12",
        "url": "/assets/templates/monograms/monograms-12.svg"
      }
    ]
  },
  {
    "key": "save-the-date",
    "label": "Tarihi Kaydet",
    "items": [
      {
        "id": "save-the-date-01",
        "url": "/assets/templates/save-the-date/save-the-date-01.svg"
      },
      {
        "id": "save-the-date-02",
        "url": "/assets/templates/save-the-date/save-the-date-02.svg"
      },
      {
        "id": "save-the-date-03",
        "url": "/assets/templates/save-the-date/save-the-date-03.svg"
      },
      {
        "id": "save-the-date-04",
        "url": "/assets/templates/save-the-date/save-the-date-04.svg"
      },
      {
        "id": "save-the-date-05",
        "url": "/assets/templates/save-the-date/save-the-date-05.svg"
      },
      {
        "id": "save-the-date-06",
        "url": "/assets/templates/save-the-date/save-the-date-06.svg"
      },
      {
        "id": "save-the-date-07",
        "url": "/assets/templates/save-the-date/save-the-date-07.svg"
      },
      {
        "id": "save-the-date-08",
        "url": "/assets/templates/save-the-date/save-the-date-08.svg"
      },
      {
        "id": "save-the-date-09",
        "url": "/assets/templates/save-the-date/save-the-date-09.svg"
      },
      {
        "id": "save-the-date-10",
        "url": "/assets/templates/save-the-date/save-the-date-10.svg"
      },
      {
        "id": "save-the-date-11",
        "url": "/assets/templates/save-the-date/save-the-date-11.svg"
      },
      {
        "id": "save-the-date-12",
        "url": "/assets/templates/save-the-date/save-the-date-12.svg"
      }
    ]
  },
  {
    "key": "engagement",
    "label": "Nişan",
    "items": [
      {
        "id": "engagement-01",
        "url": "/assets/templates/engagement/engagement-01.svg"
      },
      {
        "id": "engagement-02",
        "url": "/assets/templates/engagement/engagement-02.svg"
      },
      {
        "id": "engagement-03",
        "url": "/assets/templates/engagement/engagement-03.svg"
      },
      {
        "id": "engagement-04",
        "url": "/assets/templates/engagement/engagement-04.svg"
      },
      {
        "id": "engagement-05",
        "url": "/assets/templates/engagement/engagement-05.svg"
      },
      {
        "id": "engagement-06",
        "url": "/assets/templates/engagement/engagement-06.svg"
      },
      {
        "id": "engagement-07",
        "url": "/assets/templates/engagement/engagement-07.svg"
      },
      {
        "id": "engagement-08",
        "url": "/assets/templates/engagement/engagement-08.svg"
      },
      {
        "id": "engagement-09",
        "url": "/assets/templates/engagement/engagement-09.svg"
      },
      {
        "id": "engagement-10",
        "url": "/assets/templates/engagement/engagement-10.svg"
      },
      {
        "id": "engagement-11",
        "url": "/assets/templates/engagement/engagement-11.svg"
      },
      {
        "id": "engagement-12",
        "url": "/assets/templates/engagement/engagement-12.svg"
      }
    ]
  },
  {
    "key": "henna-night",
    "label": "Kına Gecesi",
    "items": [
      {
        "id": "henna-night-01",
        "url": "/assets/templates/henna-night/henna-night-01.svg"
      },
      {
        "id": "henna-night-02",
        "url": "/assets/templates/henna-night/henna-night-02.svg"
      },
      {
        "id": "henna-night-03",
        "url": "/assets/templates/henna-night/henna-night-03.svg"
      },
      {
        "id": "henna-night-04",
        "url": "/assets/templates/henna-night/henna-night-04.svg"
      },
      {
        "id": "henna-night-05",
        "url": "/assets/templates/henna-night/henna-night-05.svg"
      },
      {
        "id": "henna-night-06",
        "url": "/assets/templates/henna-night/henna-night-06.svg"
      },
      {
        "id": "henna-night-07",
        "url": "/assets/templates/henna-night/henna-night-07.svg"
      },
      {
        "id": "henna-night-08",
        "url": "/assets/templates/henna-night/henna-night-08.svg"
      },
      {
        "id": "henna-night-09",
        "url": "/assets/templates/henna-night/henna-night-09.svg"
      },
      {
        "id": "henna-night-10",
        "url": "/assets/templates/henna-night/henna-night-10.svg"
      },
      {
        "id": "henna-night-11",
        "url": "/assets/templates/henna-night/henna-night-11.svg"
      },
      {
        "id": "henna-night-12",
        "url": "/assets/templates/henna-night/henna-night-12.svg"
      }
    ]
  },
  {
    "key": "botanical-frames",
    "label": "Botanik Çerçeve",
    "items": [
      {
        "id": "botanical-frames-01",
        "url": "/assets/templates/botanical-frames/botanical-frames-01.svg"
      },
      {
        "id": "botanical-frames-02",
        "url": "/assets/templates/botanical-frames/botanical-frames-02.svg"
      },
      {
        "id": "botanical-frames-03",
        "url": "/assets/templates/botanical-frames/botanical-frames-03.svg"
      },
      {
        "id": "botanical-frames-04",
        "url": "/assets/templates/botanical-frames/botanical-frames-04.svg"
      },
      {
        "id": "botanical-frames-05",
        "url": "/assets/templates/botanical-frames/botanical-frames-05.svg"
      },
      {
        "id": "botanical-frames-06",
        "url": "/assets/templates/botanical-frames/botanical-frames-06.svg"
      },
      {
        "id": "botanical-frames-07",
        "url": "/assets/templates/botanical-frames/botanical-frames-07.svg"
      },
      {
        "id": "botanical-frames-08",
        "url": "/assets/templates/botanical-frames/botanical-frames-08.svg"
      },
      {
        "id": "botanical-frames-09",
        "url": "/assets/templates/botanical-frames/botanical-frames-09.svg"
      },
      {
        "id": "botanical-frames-10",
        "url": "/assets/templates/botanical-frames/botanical-frames-10.svg"
      },
      {
        "id": "botanical-frames-11",
        "url": "/assets/templates/botanical-frames/botanical-frames-11.svg"
      },
      {
        "id": "botanical-frames-12",
        "url": "/assets/templates/botanical-frames/botanical-frames-12.svg"
      }
    ]
  },
  {
    "key": "floral-corners",
    "label": "Çiçekli Köşe",
    "items": [
      {
        "id": "floral-corners-01",
        "url": "/assets/templates/floral-corners/floral-corners-01.svg"
      },
      {
        "id": "floral-corners-02",
        "url": "/assets/templates/floral-corners/floral-corners-02.svg"
      },
      {
        "id": "floral-corners-03",
        "url": "/assets/templates/floral-corners/floral-corners-03.svg"
      },
      {
        "id": "floral-corners-04",
        "url": "/assets/templates/floral-corners/floral-corners-04.svg"
      },
      {
        "id": "floral-corners-05",
        "url": "/assets/templates/floral-corners/floral-corners-05.svg"
      },
      {
        "id": "floral-corners-06",
        "url": "/assets/templates/floral-corners/floral-corners-06.svg"
      },
      {
        "id": "floral-corners-07",
        "url": "/assets/templates/floral-corners/floral-corners-07.svg"
      },
      {
        "id": "floral-corners-08",
        "url": "/assets/templates/floral-corners/floral-corners-08.svg"
      },
      {
        "id": "floral-corners-09",
        "url": "/assets/templates/floral-corners/floral-corners-09.svg"
      },
      {
        "id": "floral-corners-10",
        "url": "/assets/templates/floral-corners/floral-corners-10.svg"
      },
      {
        "id": "floral-corners-11",
        "url": "/assets/templates/floral-corners/floral-corners-11.svg"
      },
      {
        "id": "floral-corners-12",
        "url": "/assets/templates/floral-corners/floral-corners-12.svg"
      }
    ]
  },
  {
    "key": "gold-ornaments",
    "label": "Altın Süsleme",
    "items": [
      {
        "id": "gold-ornaments-01",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-01.svg"
      },
      {
        "id": "gold-ornaments-02",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-02.svg"
      },
      {
        "id": "gold-ornaments-03",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-03.svg"
      },
      {
        "id": "gold-ornaments-04",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-04.svg"
      },
      {
        "id": "gold-ornaments-05",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-05.svg"
      },
      {
        "id": "gold-ornaments-06",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-06.svg"
      },
      {
        "id": "gold-ornaments-07",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-07.svg"
      },
      {
        "id": "gold-ornaments-08",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-08.svg"
      },
      {
        "id": "gold-ornaments-09",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-09.svg"
      },
      {
        "id": "gold-ornaments-10",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-10.svg"
      },
      {
        "id": "gold-ornaments-11",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-11.svg"
      },
      {
        "id": "gold-ornaments-12",
        "url": "/assets/templates/gold-ornaments/gold-ornaments-12.svg"
      }
    ]
  },
  {
    "key": "dividers",
    "label": "Ayraç",
    "items": [
      {
        "id": "dividers-01",
        "url": "/assets/templates/dividers/dividers-01.svg"
      },
      {
        "id": "dividers-02",
        "url": "/assets/templates/dividers/dividers-02.svg"
      },
      {
        "id": "dividers-03",
        "url": "/assets/templates/dividers/dividers-03.svg"
      },
      {
        "id": "dividers-04",
        "url": "/assets/templates/dividers/dividers-04.svg"
      },
      {
        "id": "dividers-05",
        "url": "/assets/templates/dividers/dividers-05.svg"
      },
      {
        "id": "dividers-06",
        "url": "/assets/templates/dividers/dividers-06.svg"
      },
      {
        "id": "dividers-07",
        "url": "/assets/templates/dividers/dividers-07.svg"
      },
      {
        "id": "dividers-08",
        "url": "/assets/templates/dividers/dividers-08.svg"
      },
      {
        "id": "dividers-09",
        "url": "/assets/templates/dividers/dividers-09.svg"
      },
      {
        "id": "dividers-10",
        "url": "/assets/templates/dividers/dividers-10.svg"
      },
      {
        "id": "dividers-11",
        "url": "/assets/templates/dividers/dividers-11.svg"
      },
      {
        "id": "dividers-12",
        "url": "/assets/templates/dividers/dividers-12.svg"
      }
    ]
  },
  {
    "key": "wax-seals",
    "label": "Mühür",
    "items": [
      {
        "id": "wax-seals-01",
        "url": "/assets/templates/wax-seals/wax-seals-01.svg"
      },
      {
        "id": "wax-seals-02",
        "url": "/assets/templates/wax-seals/wax-seals-02.svg"
      },
      {
        "id": "wax-seals-03",
        "url": "/assets/templates/wax-seals/wax-seals-03.svg"
      },
      {
        "id": "wax-seals-04",
        "url": "/assets/templates/wax-seals/wax-seals-04.svg"
      },
      {
        "id": "wax-seals-05",
        "url": "/assets/templates/wax-seals/wax-seals-05.svg"
      },
      {
        "id": "wax-seals-06",
        "url": "/assets/templates/wax-seals/wax-seals-06.svg"
      },
      {
        "id": "wax-seals-07",
        "url": "/assets/templates/wax-seals/wax-seals-07.svg"
      },
      {
        "id": "wax-seals-08",
        "url": "/assets/templates/wax-seals/wax-seals-08.svg"
      },
      {
        "id": "wax-seals-09",
        "url": "/assets/templates/wax-seals/wax-seals-09.svg"
      },
      {
        "id": "wax-seals-10",
        "url": "/assets/templates/wax-seals/wax-seals-10.svg"
      },
      {
        "id": "wax-seals-11",
        "url": "/assets/templates/wax-seals/wax-seals-11.svg"
      },
      {
        "id": "wax-seals-12",
        "url": "/assets/templates/wax-seals/wax-seals-12.svg"
      }
    ]
  },
  {
    "key": "badges",
    "label": "Rozet",
    "items": [
      {
        "id": "badges-01",
        "url": "/assets/templates/badges/badges-01.svg"
      },
      {
        "id": "badges-02",
        "url": "/assets/templates/badges/badges-02.svg"
      },
      {
        "id": "badges-03",
        "url": "/assets/templates/badges/badges-03.svg"
      },
      {
        "id": "badges-04",
        "url": "/assets/templates/badges/badges-04.svg"
      },
      {
        "id": "badges-05",
        "url": "/assets/templates/badges/badges-05.svg"
      },
      {
        "id": "badges-06",
        "url": "/assets/templates/badges/badges-06.svg"
      },
      {
        "id": "badges-07",
        "url": "/assets/templates/badges/badges-07.svg"
      },
      {
        "id": "badges-08",
        "url": "/assets/templates/badges/badges-08.svg"
      },
      {
        "id": "badges-09",
        "url": "/assets/templates/badges/badges-09.svg"
      },
      {
        "id": "badges-10",
        "url": "/assets/templates/badges/badges-10.svg"
      },
      {
        "id": "badges-11",
        "url": "/assets/templates/badges/badges-11.svg"
      },
      {
        "id": "badges-12",
        "url": "/assets/templates/badges/badges-12.svg"
      }
    ]
  },
  {
    "key": "business-luxe",
    "label": "Minimal Lüks",
    "items": [
      {
        "id": "business-luxe-01",
        "url": "/assets/templates/business-luxe/business-luxe-01.svg"
      },
      {
        "id": "business-luxe-02",
        "url": "/assets/templates/business-luxe/business-luxe-02.svg"
      },
      {
        "id": "business-luxe-03",
        "url": "/assets/templates/business-luxe/business-luxe-03.svg"
      },
      {
        "id": "business-luxe-04",
        "url": "/assets/templates/business-luxe/business-luxe-04.svg"
      },
      {
        "id": "business-luxe-05",
        "url": "/assets/templates/business-luxe/business-luxe-05.svg"
      },
      {
        "id": "business-luxe-06",
        "url": "/assets/templates/business-luxe/business-luxe-06.svg"
      },
      {
        "id": "business-luxe-07",
        "url": "/assets/templates/business-luxe/business-luxe-07.svg"
      },
      {
        "id": "business-luxe-08",
        "url": "/assets/templates/business-luxe/business-luxe-08.svg"
      },
      {
        "id": "business-luxe-09",
        "url": "/assets/templates/business-luxe/business-luxe-09.svg"
      },
      {
        "id": "business-luxe-10",
        "url": "/assets/templates/business-luxe/business-luxe-10.svg"
      },
      {
        "id": "business-luxe-11",
        "url": "/assets/templates/business-luxe/business-luxe-11.svg"
      },
      {
        "id": "business-luxe-12",
        "url": "/assets/templates/business-luxe/business-luxe-12.svg"
      }
    ]
  },
  {
    "key": "baby-shower",
    "label": "Bebek Mevlüdü",
    "items": [
      {
        "id": "baby-shower-01",
        "url": "/assets/templates/baby-shower/baby-shower-01.svg"
      },
      {
        "id": "baby-shower-02",
        "url": "/assets/templates/baby-shower/baby-shower-02.svg"
      },
      {
        "id": "baby-shower-03",
        "url": "/assets/templates/baby-shower/baby-shower-03.svg"
      },
      {
        "id": "baby-shower-04",
        "url": "/assets/templates/baby-shower/baby-shower-04.svg"
      },
      {
        "id": "baby-shower-05",
        "url": "/assets/templates/baby-shower/baby-shower-05.svg"
      },
      {
        "id": "baby-shower-06",
        "url": "/assets/templates/baby-shower/baby-shower-06.svg"
      },
      {
        "id": "baby-shower-07",
        "url": "/assets/templates/baby-shower/baby-shower-07.svg"
      },
      {
        "id": "baby-shower-08",
        "url": "/assets/templates/baby-shower/baby-shower-08.svg"
      },
      {
        "id": "baby-shower-09",
        "url": "/assets/templates/baby-shower/baby-shower-09.svg"
      },
      {
        "id": "baby-shower-10",
        "url": "/assets/templates/baby-shower/baby-shower-10.svg"
      },
      {
        "id": "baby-shower-11",
        "url": "/assets/templates/baby-shower/baby-shower-11.svg"
      },
      {
        "id": "baby-shower-12",
        "url": "/assets/templates/baby-shower/baby-shower-12.svg"
      }
    ]
  },
  {
    "key": "kids-party",
    "label": "Çocuk Partisi",
    "items": [
      {
        "id": "kids-party-01",
        "url": "/assets/templates/kids-party/kids-party-01.svg"
      },
      {
        "id": "kids-party-02",
        "url": "/assets/templates/kids-party/kids-party-02.svg"
      },
      {
        "id": "kids-party-03",
        "url": "/assets/templates/kids-party/kids-party-03.svg"
      },
      {
        "id": "kids-party-04",
        "url": "/assets/templates/kids-party/kids-party-04.svg"
      },
      {
        "id": "kids-party-05",
        "url": "/assets/templates/kids-party/kids-party-05.svg"
      },
      {
        "id": "kids-party-06",
        "url": "/assets/templates/kids-party/kids-party-06.svg"
      },
      {
        "id": "kids-party-07",
        "url": "/assets/templates/kids-party/kids-party-07.svg"
      },
      {
        "id": "kids-party-08",
        "url": "/assets/templates/kids-party/kids-party-08.svg"
      },
      {
        "id": "kids-party-09",
        "url": "/assets/templates/kids-party/kids-party-09.svg"
      },
      {
        "id": "kids-party-10",
        "url": "/assets/templates/kids-party/kids-party-10.svg"
      },
      {
        "id": "kids-party-11",
        "url": "/assets/templates/kids-party/kids-party-11.svg"
      },
      {
        "id": "kids-party-12",
        "url": "/assets/templates/kids-party/kids-party-12.svg"
      }
    ]
  },
  {
    "key": "circumcision-classic",
    "label": "Sünnet Klasik",
    "items": [
      {
        "id": "circumcision-classic-01",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-01.svg"
      },
      {
        "id": "circumcision-classic-02",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-02.svg"
      },
      {
        "id": "circumcision-classic-03",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-03.svg"
      },
      {
        "id": "circumcision-classic-04",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-04.svg"
      },
      {
        "id": "circumcision-classic-05",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-05.svg"
      },
      {
        "id": "circumcision-classic-06",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-06.svg"
      },
      {
        "id": "circumcision-classic-07",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-07.svg"
      },
      {
        "id": "circumcision-classic-08",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-08.svg"
      },
      {
        "id": "circumcision-classic-09",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-09.svg"
      },
      {
        "id": "circumcision-classic-10",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-10.svg"
      },
      {
        "id": "circumcision-classic-11",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-11.svg"
      },
      {
        "id": "circumcision-classic-12",
        "url": "/assets/templates/circumcision-classic/circumcision-classic-12.svg"
      }
    ]
  }
];

export function findTemplate(id: string): DecorationTemplate | undefined {
  for (const cat of DECORATION_TEMPLATE_CATEGORIES) {
    const found = cat.items.find((i) => i.id === id);
    if (found) return found;
  }
  return undefined;
}
